### ISSUE TITLE
Wrapping the existing resolver

### ISSUE THREAD

**Issue by mortenbock** [Shazwazza/Our.Umbraco.IoC#1]
First of all, great initiative to make this easier to get started with.

Would it make sense to use a pattern where Umbracos own resolver is just wrapped by the custom containers?

That way there wouldn't be any need to maintain the `UmbracoServices.cs` class, because the core will just resolve those for os.

For example, in this line:

https://github.com/Shazwazza/Our.Umbraco.IoC/blob/705f623dd702b785f9bd12cbdb19d4f2dcd3d204/src/Our.Umbraco.IoC.Autofac/AutofacStartup.cs#L54

You could get the existing resolver, and pass that as a parameter to the `AutofacDependencyResolver`. Then the `AutofacDependencyResolver` can try to resolve a dependency from it's own configuration, and if it fails to do so, just delegate the call to the original DependencyResolver.

**Comment by Shazwazza** [comment]
Umbraco Core doesn't do this, it has not container and doesn't set any resolver.

**Comment by Shazwazza** [comment]
In v8, this would be possible but in v7 there won't be any container added to the core

**Comment by mortenbock** [comment]
Umbraco may not set a resolver, but Mvc comes with it's own, which is able to resolve Umbracos controllers.

So by doing something like this:

    public class MyStartup : IApplicationEventHandler
    {
        public void OnApplicationInitialized(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
        }

        public void OnApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
        }

        public void OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            var currentResolver = DependencyResolver.Current;
            var currentApiResolver = GlobalConfiguration.Configuration.DependencyResolver;
            var configurationDependencyResolver = new MyResolver(currentResolver, currentApiResolver);
            DependencyResolver.SetResolver(configurationDependencyResolver);

            GlobalConfiguration.Configuration.DependencyResolver = configurationDependencyResolver;
        }
    }

    public class MyResolver : IDependencyResolver, System.Web.Http.Dependencies.IDependencyResolver
    {
        private readonly IDependencyResolver _currentResolver;
        private readonly System.Web.Http.Dependencies.IDependencyResolver _currentApiResolver;

        public MyResolver(IDependencyResolver currentResolver,
            System.Web.Http.Dependencies.IDependencyResolver currentApiResolver)
        {
            _currentResolver = currentResolver;
            _currentApiResolver = currentApiResolver;
        }

        public object GetService(Type serviceType)
        {
            //TODO: Try to fetch service from own IoC container
            return _currentResolver.GetService(serviceType) ?? _currentApiResolver.GetService(serviceType);
        }

        public IEnumerable<object> GetServices(Type serviceType)
        {
            //TODO: Try to fetch services from own IoC container
            IEnumerable<object> services = _currentResolver.GetServices(serviceType);
            if (!(services?.Any() == true))
                services = _currentApiResolver.GetServices(serviceType);

            return services ?? new object[0];
        }

        public IDependencyScope BeginScope()
        {
            return _currentApiResolver.BeginScope();
        }

        public void Dispose()
        {
            _currentApiResolver.Dispose();
            _currentResolver.DisposeIfDisposable();
        }
    }

You won't have to do something like this for each IoC implementation:

https://github.com/Shazwazza/Our.Umbraco.IoC/blob/705f623dd702b785f9bd12cbdb19d4f2dcd3d204/src/Our.Umbraco.IoC.Autofac/AutofacStartup.cs#L45-L46

So then I can register my own stuff for the container, not having to know which assembly contains Umbracos controllers.

**Comment by Shazwazza** [comment]
There's a few things to note about this:

* The default MVC and WebApi Dependency Resolver don't do anything smart, they literally just do: `Activator.CreateInstance` which means it will only work for anything that has parameterless constructors. This means that Dependency Injection is not being done whatsoever. 
* The Dependency Resolvers do not know anything about object management or object lifetime scopes, they are *not* containers, they are purely work-arounds to be able to make DI work for MVC and WebApi by using the Service Locator pattern.

By doing the above you are actually bypassing all features of DI/IoC for all Controllers not specifically registered with your own controller which means that if you wanted to register your own implementation for a desired service, this will *not* be used for controllers not registered. Doing this also means that there is no way your container can know what the scope of the object is supposed to be and whether or not it should be managed and disposed of by your container.

The purpose of this project is so that you don't need to do anything specific for Umbraco for your own IoC implementation. 

> You won't have to do something like this for each IoC implementation:
> builder.RegisterControllers(typeof(UmbracoApplication).Assembly); 
> builder.RegisterApiControllers(typeof(UmbracoApplication).Assembly); 

... exactly, this project will ensure that all required Umbraco services are registered in the container so you don't have to manage any of it, only your own services.

**Comment by mortenbock** [comment]
Ok, I get where you are going with this. 

I was not expecting this to be the entry point for swapping out umbraco core services. I was just seeing an issue where this project would need to be aware of any changes to the core, that would mean having to change the way the Umbraco services are registered. So that would also mean that versions of the package will need to be in sync with core updates, in case there are changes that only should be registered in some versions.

Bypassing DI/IoC for anything but my own code was the intent of my suggestion. I don't want to make decisions about the lifestyle or scope of core controllers/services, so that is why I just wanted to resolve them however they would normally be resolved.

**Comment by Shazwazza** [comment]
Yup, if there are specific core changes needed, this library would need to be updated but only in one place. The chances of that happening are quite rare but it's also very easy to update and release this package.
